[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build>=0.13",
    "numpy==1.26.0",
    "scipy>=1.1.0",
    "setuptools-scm",
    "pybind11>=2.2.3",
    "pytest",
    "pytest-cov",
    "pytest-mock"
]
build-backend = "setuptools.build_meta"

[project]

name = "ac_segmentation"
version = "0.0.2"
authors = [
    {name = "Olga Gliko"},
]
description = "Segmentation for Axonal Connectomics"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-mock",
    "pytest-cov",
    "codecov",
]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
ac_segmentation = { path = ".", editable = true }

# version-specific python features
[tool.pixi.feature.py39.dependencies]
python = "3.9.*"
[tool.pixi.feature.py310.dependencies]
python = "3.10.*"

[tool.pixi.feature.scalene.dependencies]
scalene = "*"

[tool.pixi.environments]
py39-conda-scalene = ["scalene", "py39","segment"]
py310-conda-scalene = ["scalene", "py310", "segment"]
py39-conda-test = ["py39","test"]
py310-conda-test = ["py310", "test"]

[tool.coverage.run]
omit = ["test/*",]

[tool.pixi.feature.test.tasks]
test = "pytest  --cov --cov-report=xml --junitxml=test-reports/test.xml"

[tool.pixi.feature.segment.tasks]
segment = "python src/ac_segmentation/process/segment_array.py"


