[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build>=0.13",
    "numpy>=1.16.0",
    "scipy>=1.1.0",
    "setuptools-scm",
    "pybind11>=2.2.3"
]
build-backend = "setuptools.build_meta"


[project]
name = "ac_segmentation"
authors = [
    {name = "Olga Gliko"},
]
description = "Segmentation for Axonal Connectomics"

dynamic = ["version"]

dependencies = [
    "numpy>=1.16.0",
    "scikit-build>=0.13",
    "cloud-files",
    "torch==1.13.1",
    "tifffile==2023.1.23.1",
    "h5py>=2.7.1",
    "psutil>=5.4.7",
    "natsort>=7.0.0",
    "opencv-python-headless",
    "scikit-image>=0.14.2",
    "scikit-learn",
    "pandas",
    "joblib",
    "navis"
]