[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build>=0.13",
    "numpy",
    "scipy>=1.1.0",
    "setuptools-scm",
    "pybind11>=2.2.3",
    "pytest",
    "pytest-cov",
    "pytest-mock"
]
build-backend = "setuptools.build_meta"

[project]
name = "ac_segmentation"
version = "0.0.1"
authors = [
    {name = "Olga Gliko"},
]
description = "Segmentation for Axonal Connectomics"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-mock",
    "pytest-cov",
    "codecov",
]

[tool.flake8]
ignore = ['E226', 'E126', 'E741']
max-line-length = 79

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
gcc = "*"
numpy = ">=1.26,<2"

[tool.pixi.pypi-dependencies]
ac_segmentation = { path = ".", editable = true }


[tool.pixi.feature.py310.dependencies]
python = "3.10.*"
gcc = "*"

[tool.pixi.feature.scalene.dependencies]
scalene = "*"

[tool.pixi.feature.segment.dependencies]
# add any segment-specific conda packages here if needed

[tool.pixi.feature.segment.tasks]
segment = "python src/ac_segmentation/process/segment_array.py"
pytest = "pytest"

[tool.pixi.feature.test.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"

[tool.pixi.feature.test.tasks]
test = "pytest --cov --cov-report=xml --junitxml=test-reports/test.xml"

[tool.pixi.environments]
default = { features = ["py310"], solve-group = "py310" }
py310-conda-scalene = { features = ["scalene", "py310", "segment"], solve-group = "py310" }
py310-conda-test = { features = ["py310", "test"], solve-group = "py310" }

[tool.coverage.run]
omit = ["test/*"]




